# Generated by Django 4.2.6 on 2023-11-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(blank=True, max_length=100, null=True)),
                ('Pname', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Descp', models.CharField(blank=True, max_length=100, null=True)),
                ('Imges', models.ImageField(blank=True, null=True, upload_to='proImages')),
            ],
        ),
    ]
