# Generated by Django 4.2.7 on 2023-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_reg_db_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('proname', models.CharField(blank=True, max_length=100, null=True)),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reg_db',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
