# Generated by Django 4.2.7 on 2023-12-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_cart_db_alter_reg_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_db',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
