# Generated by Django 4.2.7 on 2023-12-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_reg_db_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg_db',
            new_name='rege_db',
        ),
    ]
