# Generated by Django 4.2.7 on 2023-12-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_reg_db_rege_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rege_db',
            new_name='reg_db',
        ),
    ]
