# Generated by Django 4.2.7 on 2024-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_rename_rege_db_reg_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lname', models.CharField(blank=True, max_length=100, null=True)),
                ('Addr', models.CharField(blank=True, max_length=100, null=True)),
                ('Town', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('passcode', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
